-- AlterTable
ALTER TABLE "asset_fieldOfficer_req" ADD COLUMN     "acquisition" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "apreciation_method" TEXT,
ADD COLUMN     "area" TEXT,
ADD COLUMN     "asset_sub_category_name" TEXT,
ADD COLUMN     "assets_category_type" TEXT,
ADD COLUMN     "blue_print" TEXT,
ADD COLUMN     "depreciation_method" TEXT,
ADD COLUMN     "from_whom_acquired" TEXT,
ADD COLUMN     "khata_no" TEXT,
ADD COLUMN     "mode_of_acquisition" TEXT,
ADD COLUMN     "order_date" TEXT,
ADD COLUMN     "order_no" TEXT,
ADD COLUMN     "ownership_doc" TEXT,
ADD COLUMN     "plot_no" TEXT,
ADD COLUMN     "status" INTEGER DEFAULT 0,
ADD COLUMN     "type_of_assets" TEXT,
ADD COLUMN     "type_of_land" TEXT,
ADD COLUMN     "ward_no" TEXT;
