-- AlterTable
ALTER TABLE "details" ALTER COLUMN "index" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "length" DROP NOT NULL,
ALTER COLUMN "breadth" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL;

-- AlterTable
ALTER TABLE "floorData" ALTER COLUMN "floor" DROP NOT NULL,
ALTER COLUMN "plotCount" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL;
